FROM rust:1-alpine AS builder
RUN apk add --no-cache git musl-dev openssl-dev pkgconfig protobuf-dev
ARG CDK_COMMIT=master
RUN git clone https://github.com/cashubtc/cdk.git /cdk \
    && cd /cdk \
    && git checkout ${CDK_COMMIT}
WORKDIR /cdk
RUN cargo build --release --bin cdk-mintd

FROM alpine:latest
RUN apk add --no-cache ca-certificates
COPY --from=builder /cdk/target/release/cdk-mintd /usr/local/bin/cdk-mintd
ENTRYPOINT ["cdk-mintd"]
